# This docker compose serves as easy setup of all neccessary services - databases and observation tools.

services:
  mongodb:
    image: mongo:6.0
    container_name: MongoDB
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - "${MONGO_DB_VOLUME}:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    restart: always
    cpus: "${MONGO_CPU_LIMIT:-1.0}"
    mem_limit: "${MONGO_MEM_LIMIT:-1g}"
    networks:
      - planetary-backend

  redis:
    image: redis:latest
    container_name: Redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - "${REDIS_VOLUME}:/data"
    restart: always
    command: redis-server --save 60 1 --loglevel warning
    cpus: "${REDIS_CPU_LIMIT:-0.50}"
    mem_limit: "${REDIS_MEM_LIMIT:-512m}"
    networks:
      - planetary-backend

  flower:
    image: mher/flower
    container_name: Flower
    restart: always
    ports:
      - "${FLOWER_PORT}:5555"
    environment:
      - CELERY_BROKER_URL=${FLOWER_REDIS_URL}
    depends_on:
      - redis
    networks:
      - planetary-backend

volumes:
  redis_data:
    driver: local

networks:
  planetary-backend:
    driver: bridge
