########## BUILD ##########
FROM python:3.9-slim AS builder

WORKDIR /app

# Build-time environment
ENV DEBIAN_FRONTEND=noninteractive \
    TZ=UTC \
    TERM=xterm-256color


RUN apt-get update && apt-get install -y --no-install-recommends \
    software-properties-common \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY poetry.lock pyproject.toml /app/
RUN python3.9 -m venv /app/venv && \
    /app/venv/bin/pip install --upgrade pip poetry && \
    . /app/venv/bin/activate && poetry install --no-root

COPY src /app/src
COPY worker_entrypoint.sh /app/worker_entrypoint.sh


########## RUNTIME ##########
FROM python:3.9-slim AS runtime

WORKDIR /app

ENV PYTHONUNBUFFERED=1 \
    TZ=UTC \
    LANG=en_US.UTF-8 \
    PATH="/app/venv/bin:$PATH"

# Install runtime deps only (includes gdal-bin if needed at runtime)
RUN apt-get update && apt-get install -y --no-install-recommends \
    tzdata \
    # This dude is an offender, we might want to make a separate image with this
    # when custom elevation models are needed on-the-fly
    gdal-bin \
    ncurses-bin \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /app /app

ENTRYPOINT ["/bin/bash", "/app/worker_entrypoint.sh"]
