[tool.poetry]
name = "PlanetaryExplorer"
package-mode = false
version = "0.0.1"
description = "A planetary explorer data tool."
authors = ["Your Name <your.email@example.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/michal-glos-brq/PlanetaryExplorer"
homepage = "https://github.com/michal-glos-brq/PlanetaryExplorer"

[tool.poetry.dependencies]
python = "^3.9"
astropy = "6.0.1"
astropy-iers-data = "0.2025.1.20.0.32.27"
beautifulsoup4 = "4.12.3"
pandas = "2.2.3"
pydantic = "2.10.4"
pydantic-core = "2.27.2"
pymongo = "4.10.1"
scikit-learn = "1.6.1"
scipy = "1.13.1"
spiceypy = "6.0.0"
tqdm = "4.67.1"
celery = {extras = ["redis"], version = "^5.4.0"}
aiohttp = "^3.12.15"
filelock = "^3.18.0"
aiofiles = "^24.1.0"
pvl = "^1.3.2"
requests-cache = "^1.2.1"

[tool.poetry.group.plot.dependencies]
plotly = "6.0.0"
seaborn = "^0.13.2"

[tool.poetry.group.dev.dependencies]
black = "^25.1.0"
pylint = "^3.3.6"
mypy = "^1.15.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ["py39"]

[tool.pylint]
max-line-length = 120
